__include__: [
  '../dfine_hgnetv2_s_coco.yml',
]

output_dir: ./outputs/japan7/dfine_hgnetv2_s

num_classes: 7
remap_mscoco_category: False
sync_bn: False

train_dataloader:
  dataset:
    img_folder: /COCO/Japan7-COCO/images/train
    ann_file: /COCO/Japan7-COCO/annotations/instances_train.json

val_dataloader:
  dataset:
    img_folder: /COCO/Japan7-COCO/images/val
    ann_file: /COCO/Japan7-COCO/annotations/instances_val.json
